select jsonb_build_object(
  'clients', (select count(*) from public.clients),
  'client_statuses', (select coalesce(jsonb_object_agg(x.status,x.total),'{}'::jsonb) from (select status::text,count(*) total from public.clients group by status) x),
  'clients_with_history', (select count(distinct c.id) from public.clients c join public.appointments a on a.client_id=c.id),
  'duplicate_phone_groups', (select count(*) from (select salon_id,regexp_replace(coalesce(phone,''),'[\s()\-]','','g') p from public.clients where nullif(phone,'') is not null group by 1,2 having count(*)>1) x),
  'duplicate_email_groups', (select count(*) from (select salon_id,lower(email) e from public.clients where nullif(email,'') is not null group by 1,2 having count(*)>1) x),
  'services', (select count(*) from public.services),
  'active_services', (select count(*) from public.services where is_active),
  'public_services', (select count(*) from public.services where is_public),
  'services_without_category', (select count(*) from public.services where category_id is null),
  'services_with_history', (select count(distinct service_id) from public.appointment_services where service_id is not null),
  'categories', (select count(*) from public.service_categories),
  'categories_with_services', (select count(distinct category_id) from public.services where category_id is not null),
  'employee_services', (select count(*) from public.employee_services),
  'active_employee_services', (select count(*) from public.employee_services where is_active),
  'cross_tenant_categories', (select count(*) from public.services s join public.service_categories c on c.id=s.category_id where s.salon_id<>c.salon_id),
  'cross_tenant_assignments', (select count(*) from public.employee_services es join public.employees e on e.id=es.employee_id join public.services s on s.id=es.service_id where es.salon_id<>e.salon_id or es.salon_id<>s.salon_id),
  'invalid_assignments', (select count(*) from public.employee_services where (custom_duration_minutes is not null and custom_duration_minutes<=0) or (custom_price is not null and custom_price<0)),
  'appointments', (select count(*) from public.appointments),
  'appointment_services', (select count(*) from public.appointment_services),
  'employees', (select count(*) from public.employees),
  'subscriptions', (select count(*) from public.subscriptions),
  'plans', (select count(*) from public.plans),
  'overrides', (select count(*) from public.billing_access_overrides),
  'notifications', (select count(*) from public.notifications),
  'reminder_deliveries', (select count(*) from public.appointment_reminder_deliveries)
);
