select jsonb_build_object(
  'salons', (select count(*) from public.salons),
  'distinct_owners', (select count(distinct s.owner_id) from public.salons s),
  'null_owners', (select count(*) from public.salons s where s.owner_id is null),
  'duplicate_owner_groups', (select count(*) from (select s.owner_id from public.salons s group by s.owner_id having count(*) > 1) d),
  'salons_without_owner_membership', (select count(*) from public.salons s where not exists (select 1 from public.salon_members sm where sm.salon_id=s.id and sm.profile_id=s.owner_id and sm.role='owner' and sm.status='active')),
  'mismatched_owner_memberships', (select count(*) from public.salon_members sm join public.salons s on s.id=sm.salon_id where sm.role='owner' and sm.profile_id<>s.owner_id),
  'salons_without_subscription', (select count(*) from public.salons s where not exists (select 1 from public.subscriptions sub where sub.salon_id=s.id)),
  'subscriptions_without_salon', (select count(*) from public.subscriptions sub where not exists (select 1 from public.salons s where s.id=sub.salon_id)),
  'memberships', (select count(*) from public.salon_members),
  'owner_memberships', (select count(*) from public.salon_members sm where sm.role='owner'),
  'subscriptions', (select count(*) from public.subscriptions),
  'onboarding_states', (select coalesce(jsonb_object_agg(x.state,x.total),'{}'::jsonb) from (select concat(s.onboarding_completed,':',s.onboarding_step) state,count(*) total from public.salons s group by 1) x),
  'subscription_statuses', (select coalesce(jsonb_object_agg(x.status,x.total),'{}'::jsonb) from (select sub.status::text status,count(*) total from public.subscriptions sub group by 1) x),
  'plan_distribution', (select coalesce(jsonb_object_agg(x.slug,x.total),'{}'::jsonb) from (select p.slug,count(*) total from public.subscriptions sub join public.plans p on p.id=sub.plan_id group by p.slug) x),
  'salons_insert_policies', (select coalesce(jsonb_agg(jsonb_build_object('name',p.policyname,'roles',p.roles,'command',p.cmd)),'[]'::jsonb) from pg_policies p where p.schemaname='public' and p.tablename='salons' and p.cmd='INSERT'),
  'salons_authenticated_insert', has_table_privilege('authenticated','public.salons','insert'),
  'members_authenticated_insert', has_table_privilege('authenticated','public.salon_members','insert'),
  'clients', (select count(*) from public.clients),
  'appointments', (select count(*) from public.appointments),
  'services', (select count(*) from public.services),
  'employees', (select count(*) from public.employees),
  'overrides', (select count(*) from public.billing_access_overrides)
);
